# This is the Cakefile for this project.
# Feel free to add Cakefiles to your own projects!

[metadata]
name = "Cakecutter"
version = "0.1.0"
description = "Cakecutter template (For rust)"
author = "Dhravya Shah"
author_email = "hello@dhravya.dev"

[filestructure]
root = [".gitignore", "Cargo.toml", "README.md", "LICENSE"]
examples = ["Python.toml"]
src = ["main.rs"]

# If you want to, you can literally write all the content here in one file but then what's the point of a "template" lol
[content]
Cargo-toml = """
[package]
name = "cakecutter"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5.8"
"""

[commands]
# Commands are run every time a new project is created.
1 = ["cargo", "install"]