[filestructure]
root = ['some_file']
another_directory = ['some.rs', 'cool.rs']

[content]
root--some_file = """ Multiline strings are cool 
                    , very, ver cool."""
another_directory--some-rs = """
    fn main() {
        println!("Hello, world!");
    }
"""