[filestructure]
# Anything inside the `root` folder will be created in the root directory
root = ['some_file']

# Make new directories and add files inside of them
another_directory = ['some.rs', 'cool.rs']
another_directory--directory_inside = ['some.rs', 'cool.rs']
f--f--f--f = ['f']

[content]
# You can also add content to the file templates
root--some_file = """ Multiline strings are cool 
                    , very, ver cool."""

# all "." are replaced by - and "/" are replaced by "--"
another_directory--some-rs = """
    fn main() {
        println!("Hello, world!");
    }
"""

[commands]
# Commands are executed in the order of the number.
1 = ["python", "--version"]
2 = ["pip", "install", "-r", "requirements.txt"]