# This is an example to show how a python project can be set up
[filestructure]
root = ['.gitignore', '.env', 'requirements.txt']
src = ['main.py']

[content]
src--main-py = """
print("Hello World")
"""
-gitignore = """target/
.env
venv/"""

requirements-txt = """requests"""

[commands]
1 = ['python', '-m', 'venv', 'venv']
2 = ['pip', 'install', '-r', 'requirements.txt']
3 = ['python', 'src/main.py']
