[metadata]
# Metadata is optional for every project. Its just to help keep track of who made what
name = "Python CakeCutter"
version = "0.1.0"
description = "Builds a Python project from a template"
author = "Dhravya Shah"
author_email = "hello@dhravya.dev"

# This is an example to show how a python project can be set up
[filestructure]
root = ['.gitignore', '.env', 'requirements.txt', 'README.md', 'LICENSE']
src = ['main.py']
# TODO: add support for dots in directory name (.github)

[content]
src--main-py = """
print("Hello World")
"""

-gitignore = """
target/
.env
venv/
"""

LICENSE = """
Whatever license you want here
"""

requirements-txt = """requests"""

[commands]
1 = ['python', '-m', 'venv', 'venv']
2 = ['pip', 'install', '-r', 'requirements.txt']
3 = ['python', 'src/main.py']
